obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.12, 0.05], [0.05, 0.12], [-0.05, 0.12], [-0.12, 0.05], [-0.12, -0.05], [-0.05, -0.12], [0.05, -0.12], [0.12, -0.05]]
#footprint: [[-0.10, -0.10], [-0.10, 0.10], [0.10, 0.10], [0.10, -0.10]]
#robot_radius: ir_of_robot
inflation_radius: 0.55
 
observation_sources: laser_scan_sensor
 
laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: /scan_restamp, marking: true, clearing: true}
